### ISSUE TITLE
ValueError: Following adapter(s) could not be found: default.

### ISSUE THREAD

**Issue by WalkingwithAI** [JY-Joy/InstantIR#1]
Hi bro, thank your excellent job, I have deployed this repo, but occured this error msg, can you tell me how to fix it? Thank you so much.

Loading checkpoint...
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\AI\Windows Installer Making\Test\InstantIR\gradio_demo\app.py", line 126, in instantir_restore
    pipe.unet.set_adapter('default')
  File "G:\AI\Windows Installer Making\Test\InstantIR\walkingwithai\lib\site-packages\diffusers\loaders\peft.py", line 171, in set_adapter
    raise ValueError(
ValueError: Following adapter(s) could not be found: default. Make sure you are passing the correct adapter name(s). current loaded adapters are: ['previewer', 'lcm']

**Comment by JY-Joy** [comment]
Hi bro, thanks for trying!
We've transferred the repo to the official account, where we are making new commits to. Please visit https://github.com/instantX-research/InstantIR and get our latest code. Sorry for the inconvenient :( The error you encountered is a naming problem which is fixed in our latest code.

**Comment by WalkingwithAI** [comment]
> Hi bro, thanks for trying! We've transferred the repo to the official account, where we are making new commits to. Please visit https://github.com/instantX-research/InstantIR and get our latest code. Sorry for the inconvenient :( The error you encountered is a naming problem which is fixed in our latest code.

Thank you. May God bless you.
